### PR TITLE
Do not forcefully enable metrics collection

### PR DESCRIPTION
**Pull request by MiniDigger**
this is bad. you completely demolish the privacy of server owners. if someone chooses to opt-out, then that is his choice and you should respect that. what you are doing now is to trample upon their freedom.

### CODE REVIEW

**Comment by RoboMWM** [comment]
Alternatively, add a config option to toggle your plugin's management of MCStats, if you wish to retain this "disable if offline" ability.

**Comment by Rocologo** [comment]
Im not enabling org.mcstats.Metrics for all plugins. I am enabling org.mstats_mh.Metrics for MobHunting. 

Check the code: https://github.com/Rocologo/MobHunting/blob/master/src/org/mcstats_mh/Metrics.java

So if you opt-out: true in the config.yml it will affect all other plugins, just not MobHunting. This is done exactly because a lot of old plugins has not updated their Metrics code.

**Comment by MiniDigger** [comment]
I checked the code, take a look at what enable actually does
https://github.com/Rocologo/MobHunting/blob/master/src/org/mcstats_mh/Metrics.java#L279-L282
if the player opted out in the config (the global PluginMetrics config as seen here https://github.com/Rocologo/MobHunting/blob/master/src/org/mcstats_mh/Metrics.java#L318) it just overrides the value. so it re-enables it for every other plugin too.

**Comment by Rocologo** [comment]
Its correct that it read the same file, but because I use org.mcstats_mh.Metrics it only overule for MobHunting. Please notice the _mh.

**Comment by electronicboy** [comment]
Well, No. Because you save the file back after you've changed it, so you affect every other plugin metrics that reads from that file after that point.

**Comment by Rocologo** [comment]
Okay, this was not my intention. I can see why this is a problem.

**Comment by Rocologo** [comment]
I have made another solution. I only enable Metrics (still forced) for MobHunting

**Pull request closed without merging**
