### PR TITLE
[WIP]Needs huge work

### PR DESCRIPTION
**Pull request by ysl3000**
- needs more progress. First steps could be moving the last 3 deps to maven repo

### CODE REVIEW

**Comment by Rocologo** [comment]
You are probably a  better developer than I am, but you are not good at motivation other people...  ;-)

Some of your changes are not that important or substantial, others are fine, some I don't understand and some are smart. Some are not that smart.... Some makes the plugin faster, some does not really change anything.

But is nice to have some fresh eyes looking at code.

Making this for all the plugins MonHunting hooks in to will make the MetricsManager method look ugly. I dont understand why you think that is important???

```
private ProtocolLibCompat protocolLibCompat;

public MetricsManager(MobHunting instance, ProtocolLibCompat protocolLibCompat) {
	this.instance = instance;
	this.instance = instance;
 	this.protocolLibCompat = protocolLibCompat;
 }
```

Because of the big number of changes you make, I think I will wait until you are almost finished. Because I will need to do a lot of testing before I can make a release.
Updating all the API's all the time take A LOT of time and in most cases it not important, since I only use a very limited number of methods. In most cases I have only updated when there has been major changes. MyPet and MythicMobs has chnaged alot over time.

**Comment by Rocologo** [comment]
Your last PR has conflicts???

**Comment by Rocologo** [comment]
I dont know how to solve the conflict?

Im not sure if it is the upper part of MobHuntingManger.java which is the new code or the lower part to keep?

**Comment by Rocologo** [comment]
Let me know when I should do the pull.... i need to go to sleep now, I have to get up early.

**Comment by ysl3000** [comment]
@Rocologo
We need to add the 3 deps to maven repo. I’ll help. 
MythicLib has some problem. We probably need to delete and add it again.

**Comment by Rocologo** [comment]
Im Danish i the timezone is currently UTC+2

https://www.timeanddate.com/worldclock/denmark/copenhagen

**Comment by Rocologo** [comment]
Where can I PM you? (I can create you on the Artifactory server, and allow you to deploy to ext-release-local and ext-snapshot-local) But I need your email so I can send you a password and userid?

The last three deps acted strange when I tried to deploy the artifacts.

**Comment by Rocologo** [comment]
PS. I am at work now, so my response time is slow.

**Comment by ysl3000** [comment]
ok, I'll message you on spigot.

**Comment by Rocologo** [comment]
Im glad to hear the its not only me who is having problems with deploying Gringotts and use it in the pom ;-)

**Comment by ysl3000** [comment]
Yeah found a way around. Now updating the classes a little bit.

**Comment by Rocologo** [comment]
Please let me know, when it is safe to do the pull. Also I would like to try to build against mc 1.12.1, which was released yesterday. (Although I know that the plugin seems to work with 1.12.1)

**Comment by Rocologo** [comment]
Please let me know, when it is safe to do the pull. Also I would like to try to build against mc 1.12.1, which was released yesterday. (Although I know that the plugin seems to work with 1.12.1)

**Comment by ysl3000** [comment]
Yes, when it's save to pull the [WIP] will get removed...

**Comment by ysl3000** [comment]
Won't finish my idea of optimizing this code. To much static abuse. Fixed a lot, but I do not recommend to use this. good night.

**Comment by Rocologo** [comment]
Okay, but then you wasted your time, because you left me in a situation where the plugin cant compile because of a broken pom.xml :-(

So I will probably need to do a roll back without all your suggestions to the code...

**Comment by Rocologo** [comment]
Failed to execute goal on project MobHunting: Could not resolve dependencies for project one.lindegaard:MobHunting:jar:5.0.3: Failed to collect dependencies at com.extrahardmode:ExtraHardMode:jar:3.12.1 -> net.coreprotect.CoreProtect:CoreProtect:jar:2.0.8: Failed to read artifact descriptor for net.coreprotect.CoreProtect:CoreProtect:jar:2.0.8: Could not transfer artifact net.coreprotect.CoreProtect:CoreProtect:pom:2.0.8 from/to fractal-ext-snap (https://fractal.lindegaard.one:8187/artifactory/ext-snapshot-local/): Failed to transfer https://fractal.lindegaard.one:8187/artifactory/ext-snapshot-local/net/coreprotect/CoreProtect/CoreProtect/2.0.8/CoreProtect-2.0.8.pom. Error code 409, Conflict -> [Help 1]
[ERROR]

**Comment by Rocologo** [comment]
I can fix the pom. but about the static stuff. Please explain why it is wrong to use static ?

**Comment by ysl3000** [comment]
http://www.eli.sdsu.edu/blog/whitneyBlog/In%20the%20Trenches/0FF4293F-DA7B-440D-8521-3671EFB73BE1.html

**Pull request merged**
